/**
 * @file version.h
 * @brief ArduRover firmware version information
 * 
 * @details This file defines the ArduRover firmware version string and version components.
 *          
 *          IMPORTANT: This file should NEVER be included directly in application code.
 *          Always use AP_Common/AP_FWVersion.h instead, which provides the proper
 *          version access interface. This file may only be included by the build system
 *          when FORCE_VERSION_H_INCLUDE is explicitly defined.
 *          
 *          The version information defined here is used for:
 *          - MAVLink AUTOPILOT_VERSION message (firmware identification)
 *          - Boot log messages (displayed to user at startup)
 *          - Autotest scripts (version validation and compatibility checks)
 *          - Ground control station compatibility detection
 *          
 * @note Version numbers are updated for each release following semantic versioning:
 *       - FW_MAJOR: Incremented for major feature releases or breaking changes
 *       - FW_MINOR: Incremented for new features and enhancements
 *       - FW_PATCH: Incremented for bug fixes and minor updates
 *       - FW_TYPE: Changes through release cycle (DEV → ALPHA → BETA → OFFICIAL)
 * 
 * @warning Do not change the format of FIRMWARE_VERSION - autotest scripts parse this line
 *          and expect the exact format: major,minor,patch,type
 * 
 * @author ArduPilot Development Team
 * @copyright Copyright (c) 2010-2025 ArduPilot.org
 */

#pragma once

/**
 * @brief Include guard to prevent direct inclusion
 * 
 * @details This preprocessor check ensures version.h is never included directly
 *          in source files. The correct way to access version information is through
 *          AP_Common/AP_FWVersion.h which provides the proper abstraction layer.
 *          
 *          FORCE_VERSION_H_INCLUDE must be defined before including this file,
 *          which is only done by specific build system components.
 * 
 * @see AP_Common/AP_FWVersion.h for the proper version access interface
 */
#ifndef FORCE_VERSION_H_INCLUDE
#error version.h should never be included directly. You probably want to include AP_Common/AP_FWVersion.h
#endif

/**
 * @brief Auto-generated version metadata from git repository
 * 
 * @details Includes git commit hash, branch information, and build timestamp.
 *          This file is automatically generated during the build process based on
 *          the current git repository state.
 */
#include "ap_version.h"

/**
 * @brief Human-readable firmware identification string
 * 
 * @details This string is displayed in:
 *          - MAVLink AUTOPILOT_VERSION message
 *          - Boot sequence log messages
 *          - Ground control station connection dialogs
 *          - Log file headers
 *          
 *          Format: "ArduRover V<major>.<minor>.<patch>-<type>"
 *          Current: "ArduRover V4.7.0-dev"
 *          
 *          The type suffix indicates the release stage:
 *          - "dev" = Development build (in-progress features)
 *          - "alpha" = Alpha release (feature complete, testing phase)
 *          - "beta" = Beta release (stabilization phase)
 *          - "" (empty) = Official stable release
 * 
 * @note This string is updated manually for each release
 */
#define THISFIRMWARE "ArduRover V4.7.0-dev"

/**
 * @brief Firmware version components for programmatic parsing
 * 
 * @details This define provides comma-separated version components that are parsed by:
 *          - Autotest scripts for version validation
 *          - Build system for compatibility checks
 *          - Firmware update utilities
 *          
 *          Format: major, minor, patch, type (exactly 4 components)
 *          Current: 4,7,0,FIRMWARE_VERSION_TYPE_DEV
 *          
 *          The values must exactly match the individual FW_MAJOR, FW_MINOR, 
 *          FW_PATCH, and FW_TYPE defines below.
 * 
 * @warning THE FOLLOWING LINE IS PARSED BY AUTOTEST SCRIPTS
 *          Do not change the format or add comments on the same line.
 *          The parser expects: #define FIRMWARE_VERSION <major>,<minor>,<patch>,<type>
 */
#define FIRMWARE_VERSION 4,7,0,FIRMWARE_VERSION_TYPE_DEV

/**
 * @brief Major version number
 * 
 * @details Incremented for major feature releases or significant architectural changes
 *          that may include breaking API changes or major new capabilities.
 *          
 *          Current value: 4 (ArduRover 4.x series)
 *          
 * @note Must match the first component of FIRMWARE_VERSION and THISFIRMWARE
 */
#define FW_MAJOR 4

/**
 * @brief Minor version number
 * 
 * @details Incremented for feature additions, enhancements, and improvements that
 *          maintain backward compatibility with the same major version.
 *          
 *          Current value: 7 (ArduRover 4.7.x series)
 *          
 * @note Must match the second component of FIRMWARE_VERSION and THISFIRMWARE
 */
#define FW_MINOR 7

/**
 * @brief Patch version number
 * 
 * @details Incremented for bug fixes, minor updates, and maintenance releases
 *          that do not add new features.
 *          
 *          Current value: 0 (initial release of 4.7 series, in development)
 *          
 * @note Must match the third component of FIRMWARE_VERSION and THISFIRMWARE
 */
#define FW_PATCH 0

/**
 * @brief Firmware release type
 * 
 * @details Indicates the maturity and release stage of the firmware:
 *          - FIRMWARE_VERSION_TYPE_DEV: Development build (current)
 *          - FIRMWARE_VERSION_TYPE_ALPHA: Alpha release (feature complete, early testing)
 *          - FIRMWARE_VERSION_TYPE_BETA: Beta release (stabilization and pre-release testing)
 *          - FIRMWARE_VERSION_TYPE_OFFICIAL: Official stable release
 *          
 *          This changes through the release cycle as the firmware progresses from
 *          development through testing to final release.
 *          
 *          Current value: FIRMWARE_VERSION_TYPE_DEV (active development)
 *          
 * @note Must match the fourth component of FIRMWARE_VERSION
 * @see AP_Common/AP_FWVersionDefine.h for type constant definitions
 */
#define FW_TYPE FIRMWARE_VERSION_TYPE_DEV

/**
 * @brief Firmware version constants and definitions
 * 
 * @details Provides version type constants (FIRMWARE_VERSION_TYPE_DEV, etc.)
 *          and other version-related definitions used throughout the codebase.
 *          
 * @see AP_Common/AP_FWVersionDefine.h for complete version type definitions
 */
#include <AP_Common/AP_FWVersionDefine.h>

/**
 * @brief Firmware validation and compatibility check definitions
 * 
 * @details Provides mechanisms for validating firmware compatibility and
 *          checking for required features or minimum versions.
 *          
 * @see AP_CheckFirmware/AP_CheckFirmwareDefine.h for validation utilities
 */
#include <AP_CheckFirmware/AP_CheckFirmwareDefine.h>
